# Helpers shared by the profile-source types (DensityProfile, ElectronProfile, NeutralAtmosphere).

# One-line provenance label, used by the show methods and written as the "source" attribute
# of the variables in inputs/atmosphere.nc.
function profile_label(p::Union{DensityProfile, ElectronProfile})
    isempty(p.origin) && return "$(nameof(typeof(p)))($(length(p.h)) points)"
    return "$(nameof(typeof(p)))($(length(p.h)) points, origin=$(p.origin))"
end
profile_label(d) = string(typeof(d))

# Sampling outside the native altitude range extrapolates silently; warn.
function warn_extrapolation(p, h_atm::AbstractVector)
    isempty(h_atm) && return nothing
    lo, hi = extrema(h_atm)
    lo >= first(p.h) && hi <= last(p.h) && return nothing
    @warn "$(profile_label(p)) is sampled outside its native altitude range: it covers " *
          "$(first(p.h) / 1e3) – $(last(p.h) / 1e3) km but is sampled over " *
          "$(lo / 1e3) – $(hi / 1e3) km. Values outside the native range are extrapolated " *
          "and may be far off; extend the source or narrow the model altitude grid if this " *
          "is not intended."
    return nothing
end

# The model's electrons argument as a callable h_atm → (; ne, Te). A file path is read here,
# once, so the result is saved by value in physics_state.jld2.
to_electron_source(p::ElectronProfile)   = p
to_electron_source(path::AbstractString) = read_iri_file(path)
to_electron_source(p::NeutralAtmosphere)    = throw(ArgumentError(
    "electrons must provide (ne, Te); got a NeutralAtmosphere, which holds neutral densities. " *
    "Pass an ElectronProfile instead (e.g. from run_iri, read_iri_file, or read_ccmc_iri)."))
to_electron_source(f)                    = require_reproducible(f, "electron_source")

# The model's neutrals argument as a NeutralAtmosphere. A file path is read here, once, rather
# than by each default species. A single density source is rejected: it would silently become
# the density of every species.
to_neutral_source(p::NeutralAtmosphere) = p
to_neutral_source(path::AbstractString) = read_msis_file(path)
to_neutral_source(p::ElectronProfile)   = throw(ArgumentError(
    "neutrals must provide neutral densities; got an ElectronProfile, which holds the " *
    "electron background. Did you swap the neutrals and electrons arguments?"))
to_neutral_source(x)                    = throw(ArgumentError(
    "neutrals must be a NeutralAtmosphere (e.g. from run_msis, read_msis_file, or " *
    "read_ccmc_msis) or a path to an MSIS file generated by AURORA; got a $(typeof(x)). " *
    "To set the density of a single species, pass it to that species instead, e.g. " *
    "N2Species(source) or model.species[:N2].density_source = source."))
