# Glue shared by the profile-source types (DensityProfile, ElectronProfile, NeutralProfile).
# Lives in its own file, included after all three types, so that methods referencing several
# of them do not depend on the include order of the iri/ and msis/ subtrees.

# One-line provenance label, used by the show methods and written as the "source" attribute
# of the variables in inputs/atmosphere.nc.
function profile_label(p::Union{DensityProfile, ElectronProfile})
    isempty(p.source) && return "$(nameof(typeof(p)))($(length(p.h)) points)"
    return "$(nameof(typeof(p)))($(length(p.h)) points, source=$(p.source))"
end
profile_label(d) = string(typeof(d))

# Warn when a profile is sampled outside its native altitude range: the PCHIP interpolation
# extrapolates there (log-space for densities), which can drift far from reality over a few
# tens of km with no other sign that anything is off.
function warn_extrapolation(p, h_atm::AbstractVector)
    isempty(h_atm) && return nothing
    lo, hi = extrema(h_atm)
    lo >= first(p.h) && hi <= last(p.h) && return nothing
    @warn "$(profile_label(p)) is sampled outside its native altitude range: it covers " *
          "$(first(p.h) / 1e3) – $(last(p.h) / 1e3) km but is sampled over " *
          "$(lo / 1e3) – $(hi / 1e3) km. Values outside the native range are extrapolated " *
          "and may be far off; extend the source or narrow the model altitude grid if this " *
          "is not intended."
    return nothing
end

# Normalize whatever was passed as the model's electrons argument into a callable
# h_atm → (ne, Te). A legacy IRI file path is read eagerly into an ElectronProfile so the
# result round-trips through physics_state.jld2. A custom callable is held to the same
# reproducibility bar as a species' density_source, for the same reason.
to_electron_source(p::ElectronProfile)   = p
to_electron_source(path::AbstractString) = read_iri_file(path)
to_electron_source(p::NeutralProfile)    = throw(ArgumentError(
    "electrons must provide (ne, Te); got a NeutralProfile, which holds neutral densities. " *
    "Pass an ElectronProfile instead (e.g. from run_iri, read_iri_file, or read_ccmc_iri)."))
to_electron_source(f)                    = require_reproducible(f, "electron_source")

# Normalize whatever was passed as the model's neutrals argument. A legacy MSIS file path is
# read eagerly, once, so the default species do not each re-read the file. Anything else is
# rejected: the argument describes the whole atmosphere, and a single density source silently
# becoming the density of every default species is exactly the kind of mistake this guards.
to_neutral_source(p::NeutralProfile)    = p
to_neutral_source(path::AbstractString) = read_msis_file(path)
to_neutral_source(p::ElectronProfile)   = throw(ArgumentError(
    "neutrals must provide neutral densities; got an ElectronProfile, which holds the " *
    "electron background. Did you swap the neutrals and electrons arguments?"))
to_neutral_source(x)                    = throw(ArgumentError(
    "neutrals must be a NeutralProfile (e.g. from run_msis, read_msis_file, or " *
    "read_ccmc_msis) or a path to an MSIS file generated by AURORA; got a $(typeof(x)). " *
    "To set the density of a single species, pass it to that species instead, e.g. " *
    "N2Species(source) or model.species[:N2].density_source = source."))
